### ISSUE TITLE
How to get raw texts of ACL_200 ?

### ISSUE THREAD

**Issue by 8X7K** [zoranmedic/DualLCR#2]
I'm sorry to ask you over and over. 

I carefully looked into the ACL datasets you provided, and realized the difference between `contexts_200.json` and `contexts_600.json` is not in `masked_text` or `citation_context` record, but in `preprocessed` record. 

Actually I'm interested in getting *raw* texts of 200 characters. I think what I have to do is detect `marker` in `citation_context` and fetch the 200 characters before and after. Am I right?

**Comment by zoranmedic** [comment]
Hey @8ma8X, yes, that's right, if you want to get _raw_ texts you should detect `marker` in `citation_context` and fetch 200 characters before and after. 
However, it might be easier to just exclude the first 400 and the last 400 characters from the text in `citation_context` field, as `marker` is positioned exactly in between 600 characters surrounding it. So, something like: `citation_context[400:-400]` would be sufficient.

Also, one thing to note is that the tokens in `preprocessed` field are actually obtained by taking 200 characters surrounding 'TARGETCIT' placeholder in the `masked_text` field. This is obviously different than reducing `citation_context` field to 200 characters, since longer citations are set to fixed length of 'OTHERCIT' placeholder, but nevertheless the result is a context of smaller size.

**Comment by 8X7K** [comment]
Nice! Your comment is substantial and helps me a lot! Thank you so much.
